### ISSUE TITLE
Export to CSS props

### ISSUE THREAD

**Issue by JosefJezek** [material-foundation/material-theme-builder#25]
Could you add export to CSS props?

```css
html {
  --md-sys-primary: #6750a4;
  --md-sys-on-primary: #ffffff;

  --md-sys-primary-container: #6750a4;
  --md-sys-on-primary-container: #21005d;

  --md-sys-secondary: #625b71;
  --md-sys-on-secondary: #ffffff;

  --md-sys-secondary-container: #625b71;
  --md-sys-on-secondary-container: #1d192b;

  --md-sys-tertiary: #7d5260;
  --md-sys-on-tertiary: #ffffff;

  --md-sys-tertiary-container: #7d5260;
  --md-sys-on-tertiary-container: #31111d;

  --md-sys-error: #b3261e;
  --md-sys-on-error: #ffffff;

  --md-sys-error-container: #b3261e;
  --md-sys-on-error-container: #410e0b;

  --md-sys-background: #fffbfe;
  --md-sys-on-background: #1c1b1f;

  --md-sys-surface: #fffbfe;
  --md-sys-on-surface: #1c1b1f;

  --md-sys-surface-variant: #e7e0ec;
  --md-sys-on-surface-variant: #49454f;

  --md-sys-inverse-primary: #fff;
  --md-sys-inverse-surface: #313033;
  --md-sys-inverse-on-surface: #f4eff4;

  --md-sys-outline: #79747e;
  --md-sys-shadow: #000000;
}

html.dark {
  --md-sys-primary: #6750a4;
  --md-sys-on-primary: #ffffff;

  --md-sys-primary-container: #6750a4;
  --md-sys-on-primary-container: #21005d;

  --md-sys-secondary: #625b71;
  --md-sys-on-secondary: #ffffff;

  --md-sys-secondary-container: #625b71;
  --md-sys-on-secondary-container: #1d192b;

  --md-sys-tertiary: #7d5260;
  --md-sys-on-tertiary: #ffffff;

  --md-sys-tertiary-container: #7d5260;
  --md-sys-on-tertiary-container: #31111d;

  --md-sys-error: #b3261e;
  --md-sys-on-error: #ffffff;

  --md-sys-error-container: #b3261e;
  --md-sys-on-error-container: #410e0b;

  --md-sys-background: #fffbfe;
  --md-sys-on-background: #1c1b1f;

  --md-sys-surface: #fffbfe;
  --md-sys-on-surface: #1c1b1f;

  --md-sys-surface-variant: #e7e0ec;
  --md-sys-on-surface-variant: #49454f;

  --md-sys-inverse-primary: #fff;
  --md-sys-inverse-surface: #313033;
  --md-sys-inverse-on-surface: #f4eff4;

  --md-sys-outline: #79747e;
  --md-sys-shadow: #000000;
}

html.high-contrast {
}

html.dark.high-contrast {
}
```
