### ISSUE TITLE
Generated CSS colors are all black

### ISSUE THREAD

**Issue by jonaaix** [material-foundation/material-theme-builder#368]
**Describe the bug**
As of today (was working until Sunday), when I export a theme for web, all colors appear to be a shade of black.

**To Reproduce**
1. Go to [https://material-foundation.github.io/material-theme-builder/](https://material-foundation.github.io/material-theme-builder/)
2. Click on Pick your fonts
3. Click on Export Theme
4. Export as Web (CSS)
5. Open `light.css` or `dark.css` in your fav code editor
**Expected behavior**
Palette should be matching with preview.

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.2
 - Browser Chrome/Firefox

**Additional context**
This is the generated content of `light.css` for input color `#63A002`
```css
.light {
  --md-sys-color-primary: rgb(0.42745098039215684 0.3686274509803922 0.058823529411764705);
  --md-sys-color-surface-tint: rgb(0.42745098039215684 0.3686274509803922 0.058823529411764705);
  --md-sys-color-on-primary: rgb(1 1 1);
  --md-sys-color-primary-container: rgb(0.9725490196078431 0.8862745098039215 0.5294117647058824);
  --md-sys-color-on-primary-container: rgb(0.3254901960784314 0.27450980392156865 0);
  --md-sys-color-secondary: rgb(0.4 0.3686274509803922 0.25098039215686274);
  --md-sys-color-on-secondary: rgb(1 1 1);
  --md-sys-color-secondary-container: rgb(0.9333333333333333 0.8862745098039215 0.7372549019607844);
  --md-sys-color-on-secondary-container: rgb(0.3058823529411765 0.2784313725490196 0.16470588235294117);
  --md-sys-color-tertiary: rgb(0.2627450980392157 0.4 0.3058823529411765);
  --md-sys-color-on-tertiary: rgb(1 1 1);
  --md-sys-color-tertiary-container: rgb(0.7725490196078432 0.9254901960784314 0.807843137254902);
  --md-sys-color-on-tertiary-container: rgb(0.17254901960784313 0.3058823529411765 0.2196078431372549);
  --md-sys-color-error: rgb(0.7294117647058823 0.10196078431372549 0.10196078431372549);
  --md-sys-color-on-error: rgb(1 1 1);
  --md-sys-color-error-container: rgb(1 0.8549019607843137 0.8392156862745098);
  --md-sys-color-on-error-container: rgb(0.5764705882352941 0 0.0392156862745098);
  --md-sys-color-background: rgb(1 0.9764705882352941 0.9333333333333333);
  --md-sys-color-on-background: rgb(0.11764705882352941 0.10588235294117647 0.07450980392156863);
  --md-sys-color-surface: rgb(1 0.9764705882352941 0.9333333333333333);
  --md-sys-color-on-surface: rgb(0.11764705882352941 0.10588235294117647 0.07450980392156863);
  --md-sys-color-surface-variant: rgb(0.9176470588235294 0.8862745098039215 0.8156862745098039);
  --md-sys-color-on-surface-variant: rgb(0.29411764705882354 0.2784313725490196 0.2235294117647059);
  --md-sys-color-outline: rgb(0.48627450980392156 0.4666666666666667 0.403921568627451);
  --md-sys-color-outline-variant: rgb(0.803921568627451 0.7764705882352941 0.7058823529411765);
  --md-sys-color-shadow: rgb(0 0 0);
  --md-sys-color-scrim: rgb(0 0 0);
  --md-sys-color-inverse-surface: rgb(0.2 0.18823529411764706 0.15294117647058825);
  --md-sys-color-inverse-on-surface: rgb(0.9686274509803922 0.9411764705882353 0.8862745098039215);
  --md-sys-color-inverse-primary: rgb(0.8588235294117647 0.7764705882352941 0.43137254901960786);
  --md-sys-color-primary-fixed: rgb(0.9725490196078431 0.8862745098039215 0.5294117647058824);
  --md-sys-color-on-primary-fixed: rgb(0.13333333333333333 0.10588235294117647 0);
  --md-sys-color-primary-fixed-dim: rgb(0.8588235294117647 0.7764705882352941 0.43137254901960786);
  --md-sys-color-on-primary-fixed-variant: rgb(0.3254901960784314 0.27450980392156865 0);
  --md-sys-color-secondary-fixed: rgb(0.9333333333333333 0.8862745098039215 0.7372549019607844);
  --md-sys-color-on-secondary-fixed: rgb(0.12941176470588237 0.10588235294117647 0.01568627450980392);
  --md-sys-color-secondary-fixed-dim: rgb(0.8196078431372549 0.7764705882352941 0.6313725490196078);
  --md-sys-color-on-secondary-fixed-variant: rgb(0.3058823529411765 0.2784313725490196 0.16470588235294117);
  --md-sys-color-tertiary-fixed: rgb(0.7725490196078432 0.9254901960784314 0.807843137254902);
  --md-sys-color-on-tertiary-fixed: rgb(0 0.12941176470588237 0.058823529411764705);
  --md-sys-color-tertiary-fixed-dim: rgb(0.6627450980392157 0.8156862745098039 0.7019607843137254);
  --md-sys-color-on-tertiary-fixed-variant: rgb(0.17254901960784313 0.3058823529411765 0.2196078431372549);
  --md-sys-color-surface-dim: rgb(0.8784313725490196 0.8509803921568627 0.8);
  --md-sys-color-surface-bright: rgb(1 0.9764705882352941 0.9333333333333333);
  --md-sys-color-surface-container-lowest: rgb(1 1 1);
  --md-sys-color-surface-container-low: rgb(0.9803921568627451 0.9529411764705882 0.8980392156862745);
  --md-sys-color-surface-container: rgb(0.9568627450980393 0.9294117647058824 0.8745098039215686);
  --md-sys-color-surface-container-high: rgb(0.9333333333333333 0.9098039215686274 0.8549019607843137);
  --md-sys-color-surface-container-highest: rgb(0.9098039215686274 0.8862745098039215 0.8313725490196079);
}

```
